version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: './docker/Dockerfile.prod'
    ports:
      - 8080:8080
  dev:
    profiles:
      - dev
    build:
      context: ..
      dockerfile: './docker/Dockerfile.dev'
    volumes:
      - '..:/app'
      - '/app/node_modules:../node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
