FROM node:19.3.0
# Create workdir
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./
COPY .yarnrc.yml ./
COPY .yarn/ ./.yarn
RUN yarn install

EXPOSE 3000

CMD ["yarn", "start"]
